pauleve/docker-mtgo

README.md, docker-wine/0001-gdi32-Also-accept-.-DISPLAY-n-devices-names-with-n-o.patch, docker-wine/0002-winex11-Make-GetMonitorInfo-give-a-different-device-.patch, docker-wine/0003-user32-Implement-EnumDisplayDevicesW-based-on-EnumDi.patch, docker-wine/0004-winemac-Make-GetMonitorInfo-give-a-different-device-.patch, docker-wine/0005-user32-Return-a-more-reasonable-display-DeviceID.patch, docker-wine/Dockerfile
May fix issue #68 showing a potential regression of recent WineHQ versions with MTGO locking for a couple of seconds on most actions
=> Switch back to wine 4.9

README.md, docker-wine/Dockerfile
=> Update wine to 5.6

README.md, docker-wine/Dockerfile
Updates wine to 5.7
```
./run-mtgo --update --test panard/mtgo:pr92
```
=> Update wine to 5.7

README.md, docker-wine/Dockerfile
=> Update wine to 5.12

Dockerfile, README.md, docker-wine/Dockerfile
=> Update wine to 5.17

docker-wine/Dockerfile
See https://bugs.winehq.org/show_bug.cgi?id=49876
=> Install libx{randr2,xinerama1,composite1}

README.md, docker-wine/Dockerfile
=> Update wine to 6.3

README.md, docker-wine/Dockerfile
=> Update wine to 6.4

README.md, docker-wine/Dockerfile
=> Update wine to 6.5

README.md, docker-wine/Dockerfile
=> Update wine to 6.11

README.md, docker-wine/Dockerfile
=> Update wine to 6.12

README.md, docker-wine/Dockerfile
=> Update wine to 6.13

README.md, docker-wine/Dockerfile
=> Update wine to 6.20

README.md, docker-wine/Dockerfile
=> Update wine to 6.22

README.md, docker-wine/Dockerfile
Updates wine to 7.0-rc1
```
```
=> Update wine to 7.0-rc1

Dockerfile, README.md, docker-wine/Dockerfile
=> Update wine to 7.7

README.md, docker-wine/Dockerfile
=> Update wine to 7.10

README.md, docker-wine/Dockerfile
=> Update wine to 7.19

Dockerfile, README.md, extra/live-mtgo, extra/mtgo.sh
```
./run-mtgo --update --reset panard/mtgo:pr161
```
=> Daybreak migration

Dockerfile, docker-wine/wine-crypt32_byname.patch, extra/mtgo.sh, run-mtgo
See https://bugs.winehq.org/show_bug.cgi?id=53813
=> Wine patch for certificate validation

README.md, docker-wine/Dockerfile
=> Update wine to 8.7

README.md, docker-wine/Dockerfile
=> Update wine to 8.10

Dockerfile, README.md, docker-wine/Dockerfile
=> Update wine to 8.15

README.md, run-mtgo
Podman is an alternative container manager, with an almost identical CLI and the same images format. 
Just adding a few changes and some lines in the FAQ  to help those that use it instead of Docker.
=> Podman support

Dockerfile
Updates wine to  9.4-wow64
```
```
=> Update wine to 9.4-wow64
